### ISSUE TITLE
order status is "pending", not yet "valid"

### ISSUE THREAD

**Issue by mdmappledev** [brandonweeks/acme-device-attest-demo#2]
We are testing Apple's ACME payload with "ca.attestation.dev" ACME server and we are getting this below error.
**order status is "pending", not yet "valid"**

Initially, we were able to get the payload working in an iPhone device, but after installing the payload 2-3 times, we started getting this error. We also tried installing the payload in another iPhone, but it didn't even work once.

Any help on this would be much appreciated. Thanks in Advance.

**Comment by brandonweeks** [comment]
There are quite a few different errors in the `ca.attestation.dev` logs. Do you know when you made one of the requests that failed? Or would you be willing to schedule some time to test this together?

**Comment by mdmappledev** [comment]
Thanks for your response. I tried the profile installation again and it failed with the below errors.

**order status is "pending", not yet "valid"**
**failed to request authorization**

This is the Client Identifier I used: **mdmappledevtest**
Tested at: **UTC Thursday, 28 July 2022, 11:10 AM to 11:20 AM**

We will be very happy to test this together. We are available from 29 July Friday, 9 AM PDT to 9PM PDT.

**Comment by mdmappledev** [comment]
Hello Brandon, Hope you are doing well.
We ran a test on this today, and received the same error. Any help on this would be helpful. Thanks for your time.

1. order status is "pending", not yet "valid"
2. order status is "ready", not yet "valid"

[ACME.pdf](https://github.com/brandonweeks/acme-device-attest-demo/files/9399359/ACME.pdf)

**Comment by mdmappledev** [comment]
We were sending out a lot of different payload combinations and didn't notice that the `Attest` was set to false. Once we changed it true, the profile worked fine.
