### ISSUE TITLE
Proof of possession with ACME device attestation

### ISSUE THREAD

**Issue by NickDarvey** [brandonweeks/acme-device-attest-demo#7]
[go-attestation](https://github.com/google/go-attestation) and [TPM 2.0 Keys for Device Identity and Attestation](https://trustedcomputinggroup.org/wp-content/uploads/TPM-2p0-Keys-for-Device-Identity-and-Attestation_v1_r12_pub10082021.pdf) talk about proving possession of AK by decrypting a challenge.

> The server uses the EK and AK parameters to generate a challenge encrypted to the EK, returning the challenge to the client. During this phase, the server determines if it trusts the EK, either by chaining its certificate to a known manufacturer and/or querying an inventory system.
> [...]
> The client proves possession of the AK by decrypting the challenge and returning the same secret to the server.

https://github.com/google/go-attestation/blob/master/README.md?plain=1#L91-L113

I don't see this done here, or rather in step-ca, or mentioned in the spec. How is possession proved with ACME device attestation?

And... maybe I'm conflating things, but is the proof-of-posession and chaining the AK to the EK the guarantee that the private key is protected by hardware?

**Comment by brandonweeks** [comment]
This repository does not contain a full implementation of an attestation CA, it merely demonstrates how a preexisting AK certificate could be used with ACME device attest to request a client certificate. I am not familiar with the implementation that landed upstream in step-ca.

An AK certificate being issued is a prerequisite to the flow described in `draft-acme-device-attest`. An organization would need to deploy both an attestation CA (I'm not aware of a standard for this) and a client certificate CA (supporting `draft-acme-device-attest`) to support devices with a TPM.

**Comment by NickDarvey** [comment]
Ahah! Okay, makes a lot of sense. Cheers. The attestation CA seems to be the big missing piece in a lot of the standards and implementations I've been seeing.
